-- 道路信息表
CREATE TABLE IF NOT EXISTS `road` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `road_code` VARCHAR(64) NOT NULL COMMENT '道路编码',
    `road_name` VARCHAR(255) NOT NULL COMMENT '道路名称',
    `road_grade` VARCHAR(32) COMMENT '道路等级：国道/省道/县道/城市主干道/城市次干道/城市支路',
    `district` VARCHAR(64) COMMENT '所属区域',
    `start_point` VARCHAR(255) COMMENT '起点',
    `end_point` VARCHAR(255) COMMENT '终点',
    `center_lng` DECIMAL(10,7) COMMENT '中心点经度',
    `center_lat` DECIMAL(10,7) COMMENT '中心点纬度',
    `length_km` DECIMAL(10,3) COMMENT '长度(km)',
    `lane_count` INT COMMENT '车道数',
    `surface_type` VARCHAR(32) COMMENT '路面类型：沥青/水泥/混合',
    `built_year` INT COMMENT '建成年代',
    `last_maintained` DATETIME COMMENT '上次养护时间',
    `health_score` DECIMAL(5,2) DEFAULT 100.00 COMMENT '健康评分(0-100)',
    `damage_level` VARCHAR(16) DEFAULT 'HEALTHY' COMMENT '病害等级：HEALTHY/SUB_HEALTHY/UNHEALTHY',
    `latest_detection_at` DATETIME COMMENT '最近检测时间',
    `total_detection_count` INT DEFAULT 0 COMMENT '累计检测次数',
    `current_damage_count` INT DEFAULT 0 COMMENT '当前病害数',
    `department_code` VARCHAR(64) COMMENT '责任部门编码',
    `status` VARCHAR(16) DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/MAINTAINING/CLOSED',
    `remark` VARCHAR(500) COMMENT '备注',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX `idx_road_name` (`road_name`),
    INDEX `idx_district` (`district`),
    INDEX `idx_road_grade` (`road_grade`),
    INDEX `idx_status` (`status`),
    INDEX `idx_department_code` (`department_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='道路信息表';
